//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculationwebapplication.Calculat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calculat.CalculatorSoap")]
    public interface CalculatorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int FN, int SN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int FN, int SN);
        
        // CODEGEN: Generating message contract since element name GetCalculstionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculstions", ReplyAction="*")]
        calculationwebapplication.Calculat.GetCalculstionsResponse GetCalculstions(calculationwebapplication.Calculat.GetCalculstionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCalculstions", ReplyAction="*")]
        System.Threading.Tasks.Task<calculationwebapplication.Calculat.GetCalculstionsResponse> GetCalculstionsAsync(calculationwebapplication.Calculat.GetCalculstionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculstionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculstions", Namespace="http://tempuri.org/", Order=0)]
        public calculationwebapplication.Calculat.GetCalculstionsRequestBody Body;
        
        public GetCalculstionsRequest() {
        }
        
        public GetCalculstionsRequest(calculationwebapplication.Calculat.GetCalculstionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculstionsRequestBody {
        
        public GetCalculstionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculstionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculstionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public calculationwebapplication.Calculat.GetCalculstionsResponseBody Body;
        
        public GetCalculstionsResponse() {
        }
        
        public GetCalculstionsResponse(calculationwebapplication.Calculat.GetCalculstionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCalculstionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public calculationwebapplication.Calculat.ArrayOfString GetCalculstionsResult;
        
        public GetCalculstionsResponseBody() {
        }
        
        public GetCalculstionsResponseBody(calculationwebapplication.Calculat.ArrayOfString GetCalculstionsResult) {
            this.GetCalculstionsResult = GetCalculstionsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorSoapChannel : calculationwebapplication.Calculat.CalculatorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorSoapClient : System.ServiceModel.ClientBase<calculationwebapplication.Calculat.CalculatorSoap>, calculationwebapplication.Calculat.CalculatorSoap {
        
        public CalculatorSoapClient() {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int FN, int SN) {
            return base.Channel.Add(FN, SN);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int FN, int SN) {
            return base.Channel.AddAsync(FN, SN);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        calculationwebapplication.Calculat.GetCalculstionsResponse calculationwebapplication.Calculat.CalculatorSoap.GetCalculstions(calculationwebapplication.Calculat.GetCalculstionsRequest request) {
            return base.Channel.GetCalculstions(request);
        }
        
        public calculationwebapplication.Calculat.ArrayOfString GetCalculstions() {
            calculationwebapplication.Calculat.GetCalculstionsRequest inValue = new calculationwebapplication.Calculat.GetCalculstionsRequest();
            inValue.Body = new calculationwebapplication.Calculat.GetCalculstionsRequestBody();
            calculationwebapplication.Calculat.GetCalculstionsResponse retVal = ((calculationwebapplication.Calculat.CalculatorSoap)(this)).GetCalculstions(inValue);
            return retVal.Body.GetCalculstionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<calculationwebapplication.Calculat.GetCalculstionsResponse> calculationwebapplication.Calculat.CalculatorSoap.GetCalculstionsAsync(calculationwebapplication.Calculat.GetCalculstionsRequest request) {
            return base.Channel.GetCalculstionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<calculationwebapplication.Calculat.GetCalculstionsResponse> GetCalculstionsAsync() {
            calculationwebapplication.Calculat.GetCalculstionsRequest inValue = new calculationwebapplication.Calculat.GetCalculstionsRequest();
            inValue.Body = new calculationwebapplication.Calculat.GetCalculstionsRequestBody();
            return ((calculationwebapplication.Calculat.CalculatorSoap)(this)).GetCalculstionsAsync(inValue);
        }
    }
}
