//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.calculatAge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://JSAhome.aspx/", ConfigurationName="calculatAge.calculateageSoap")]
    public interface calculateageSoap {
        
        // CODEGEN: Generating message contract since element name selectedDate from namespace http://JSAhome.aspx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://JSAhome.aspx/CalculateAge", ReplyAction="*")]
        WebApplication1.calculatAge.CalculateAgeResponse CalculateAge(WebApplication1.calculatAge.CalculateAgeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://JSAhome.aspx/CalculateAge", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.calculatAge.CalculateAgeResponse> CalculateAgeAsync(WebApplication1.calculatAge.CalculateAgeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateAgeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateAge", Namespace="http://JSAhome.aspx/", Order=0)]
        public WebApplication1.calculatAge.CalculateAgeRequestBody Body;
        
        public CalculateAgeRequest() {
        }
        
        public CalculateAgeRequest(WebApplication1.calculatAge.CalculateAgeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://JSAhome.aspx/")]
    public partial class CalculateAgeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string selectedDate;
        
        public CalculateAgeRequestBody() {
        }
        
        public CalculateAgeRequestBody(string selectedDate) {
            this.selectedDate = selectedDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateAgeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateAgeResponse", Namespace="http://JSAhome.aspx/", Order=0)]
        public WebApplication1.calculatAge.CalculateAgeResponseBody Body;
        
        public CalculateAgeResponse() {
        }
        
        public CalculateAgeResponse(WebApplication1.calculatAge.CalculateAgeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://JSAhome.aspx/")]
    public partial class CalculateAgeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CalculateAgeResult;
        
        public CalculateAgeResponseBody() {
        }
        
        public CalculateAgeResponseBody(int CalculateAgeResult) {
            this.CalculateAgeResult = CalculateAgeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calculateageSoapChannel : WebApplication1.calculatAge.calculateageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calculateageSoapClient : System.ServiceModel.ClientBase<WebApplication1.calculatAge.calculateageSoap>, WebApplication1.calculatAge.calculateageSoap {
        
        public calculateageSoapClient() {
        }
        
        public calculateageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calculateageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculateageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculateageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.calculatAge.CalculateAgeResponse WebApplication1.calculatAge.calculateageSoap.CalculateAge(WebApplication1.calculatAge.CalculateAgeRequest request) {
            return base.Channel.CalculateAge(request);
        }
        
        public int CalculateAge(string selectedDate) {
            WebApplication1.calculatAge.CalculateAgeRequest inValue = new WebApplication1.calculatAge.CalculateAgeRequest();
            inValue.Body = new WebApplication1.calculatAge.CalculateAgeRequestBody();
            inValue.Body.selectedDate = selectedDate;
            WebApplication1.calculatAge.CalculateAgeResponse retVal = ((WebApplication1.calculatAge.calculateageSoap)(this)).CalculateAge(inValue);
            return retVal.Body.CalculateAgeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.calculatAge.CalculateAgeResponse> WebApplication1.calculatAge.calculateageSoap.CalculateAgeAsync(WebApplication1.calculatAge.CalculateAgeRequest request) {
            return base.Channel.CalculateAgeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.calculatAge.CalculateAgeResponse> CalculateAgeAsync(string selectedDate) {
            WebApplication1.calculatAge.CalculateAgeRequest inValue = new WebApplication1.calculatAge.CalculateAgeRequest();
            inValue.Body = new WebApplication1.calculatAge.CalculateAgeRequestBody();
            inValue.Body.selectedDate = selectedDate;
            return ((WebApplication1.calculatAge.calculateageSoap)(this)).CalculateAgeAsync(inValue);
        }
    }
}
